### PR TITLE
updated the bug

### PR DESCRIPTION
**Pull request by gc824**
Fixed small bug found in #24.

### CODE REVIEW

**Comment by billythakidd04** [comment]
@gc824 , I don't understand. What IS the bug?? There's no description of what exactly you fixed...

**Comment by gc824** [comment]
> @gc824 , I don't understand. What IS the bug?? There's no description of what exactly you fixed...

In my previous PR you found a bug, so  I fixed the bug and updated the PR. 

"this shouldn't be email it should be subject I assume" 

contactus.php
			<input type="email" name="email" <?= ($email ? 'value="' . $email . '"' : ''); ?> placeholder="Your Email" required>
			<?= (isset($errors['email']) && !empty($errors['email']) ? '<span class="text-danger">' . $errors['email'] . '</span>' : ''); ?><br />
			<input type="text" name="subject" <?= ($subject ? 'value="' . $subject . '"' : ''); ?> placeholder="Subject" required><br />
			<?= (isset($subject['email']) && !empty($errors['subject']) ? '<span class="text-danger">' . $errors['subject'] . '</span>' : ''); ?><br />

**Comment by billythakidd04** [comment]
If this is to fix the changes needed to get the pr approved, those changes should be on _that_ branch so they are associated with the right pr.

**Comment by billythakidd04** [comment]
needs to be applied to the menubar branch

**Pull request closed without merging**
